# Generated by Django 3.1.7 on 2021-04-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('amount', models.FloatField()),
                ('borrowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MoneyLoan_borrower', to=settings.AUTH_USER_MODEL)),
                ('lenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MoneyLoan_lender', to=settings.AUTH_USER_MODEL)),
                ('loanStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MoneyLoan_loanStatus', to='lendapp.loanstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('itemAmount', models.IntegerField()),
                ('borrowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_borrower', to=settings.AUTH_USER_MODEL)),
                ('itemCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemCategory', to='lendapp.itemcategory')),
                ('lenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_lender', to=settings.AUTH_USER_MODEL)),
                ('loanStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_loanStatus', to='lendapp.loanstatus')),
            ],
        ),
    ]
