# Generated by Django 3.1.7 on 2021-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
