# Generated by Django 3.1.7 on 2021-04-10 11:34

import apps.lendapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0002_auto_20210409_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='image',
            field=models.ImageField(default='', upload_to=apps.lendapp.utils.user_directory_path),
            preserve_default=False,
        ),
    ]
