# Generated by Django 3.1.7 on 2021-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
