# Generated by Django 3.1.7 on 2021-04-10 12:08

import apps.lendapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0003_loan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.lendapp.utils.user_directory_path),
        ),
    ]
